### PR TITLE
Fix: Ensure external refs are propagated to generated code

### LINKED ISSUE #1378: Missing package name on type from common API spec when referencing a path operation from another spec in generated code
We're hitting a bug where generated code doesn't compile when using API specs referencing each other. This may or may not be related to #695, so I'm opening a separate issue just to be sure.

The setup is this (also available at https://github.com/maragudk/oapi-codegen-bug):

- An `api.yaml` spec references a path in a `common.yaml` spec.
- In `common.yaml`, a path `/ping` references a schema `PingResponse` in the same file.

When the spec is generated for `api.yaml`, `PingResponse` doesn't have the `externalRef0` package name prefix, and so the generated code can't compile.

This is with v2 of oapi-codegen.

**api.yaml**

```yaml
version: "3.0.0"

paths:
  /ping:
    $ref: "common.yaml#/paths/~1ping"
```

**config.yaml**

```yaml
package: api
generate:
  gin-server: true
  embedded-spec: true
  strict-server: true
  models: true
import-mapping:
  common.yaml: github.com/maragudk/oapi-codegen-bug/oapi/common
output: api.gen.go
```

**common.yaml**

```yaml
version: "3.0.0"

paths:
  /ping:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PingResponse"

components:
  schemas:
    PingResponse:
      type: object
      properties:
        message:
          type: string
```

**config.yaml**

```yaml
package: common
generate:
  gin-server: true
  embedded-spec: true
  strict-server: true
  models: true
output: common.gen.go
```

### PR DESCRIPTION
**Pull request by jamietanna**
As noted in #1378, there are cases where a complex set of `$ref`s
between multiple files can lead to broken generated code, which does not
correctly import the package that has been prepared for the external
reference.

We can handle this by looking up any references, where there is a `.Ref`
passed into the type, and then iterate through relevant children.

This requires we handle the updating in-place for these by using a bit
of pointer + indexing fun.

This also adds a relevant test case to validate the fix.

Closes #1378.

---

**Note** that this won't fix every case - we'll review it in https://github.com/deepmap/oapi-codegen/issues/1440

### CODE REVIEW

File: pkg/codegen/operations.go [hunk 1]
```diff
@@ -817,6 +821,19 @@ func GenerateResponseDefinitions(operationID string, responses map[string]*opena
 				NameTag:     tag,
 				Schema:      contentSchema,
 			}
+
+			// TODO finish comment
```
Comment (jamietanna) [inline pkg/codegen/operations.go:825]: TODO

File: pkg/codegen/operations.go [hunk 2]
```diff
@@ -817,6 +821,19 @@ func GenerateResponseDefinitions(operationID string, responses map[string]*opena
...
+			parts := strings.SplitN(parentRef, "#", 2)
+			if parentRef != "" && len(parts) == 2 {
+				// TODO finish comment
```
Comment (jamietanna) [inline pkg/codegen/operations.go:828]: TODO

**Comment by markuswustenberg** [comment]
I'm getting the following error when trying this out:

```
error generating code: error formatting Go code <generated code here> filename.go:5746:70: expected 'IDENT', found 'struct' (and 7 more errors)
```

File: pkg/codegen/operations.go [hunk 3]
```diff
@@ -817,6 +821,19 @@ func GenerateResponseDefinitions(operationID string, responses map[string]*opena
...
+				// if a locally-defined, but `$ref`'d parent, then we need to make sure that we make this an external ref
```
Comment (jamietanna) [inline pkg/codegen/operations.go:829]: rephrase

File: pkg/codegen/schema.go [hunk 4]
```diff
@@ -43,6 +43,13 @@ func (s Schema) IsRef() bool {
 	return s.RefType != ""
 }
 
+func (s Schema) IsExternalRef() bool {
+	if !s.IsRef() {
+		return false
+	}
+	return strings.Contains(s.RefType, ".")
+}
```
Comment (jamietanna) [inline pkg/codegen/schema.go:51]: unused :thinking:

Comment (jamietanna) [reply pkg/codegen/schema.go:51]: Ah, it is used, but in templates

File: internal/test/issues/issue-1378/bionicle/generate.go [hunk 5]
```diff
@@ -0,0 +1,3 @@
+package bionicle
+
+//go:generate go run github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml ../bionicle.yaml
```
Comment (markuswustenberg) [inline internal/test/issues/issue-1378/bionicle/generate.go:3]: Will this work without a Go workspace set up in the environment? Is `go generate` smart enough to know this is the same repo, and run the local version?

File: internal/test/issues/issue-1378/common/config.yaml [hunk 6]
```diff
@@ -0,0 +1,9 @@
+package: common
+generate:
+  gorilla-server: true
+  embedded-spec: true
+  strict-server: true
+  models: true
+output-options:
```
Comment (markuswustenberg) [inline internal/test/issues/issue-1378/common/config.yaml:7]: Probably not for this PR, but it would make sense to not prune code that is used in dependent APIs by default, instead of having to set this explicitly.

File: pkg/codegen/externalref.go [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+
+import (
+	"fmt"
+	"strings"
+)
+
+// ensureExternalRefsInRequestBodyDefinitions ensures that when an externalRef (`$ref` that points to a file that isn't the current spec) is encountered, we make sure we update our underlying `RefType` to make sure that we point to that type.
+// This only happens if we have a non-empty `ref` passed in, and that `ref` isn't pointing to something in our file
+// NOTE that the pointer here allows us to pass in a reference and edit in-place
+func ensureExternalRefsInRequestBodyDefinitions(defs *[]RequestBodyDefinition, ref string) {
```
Comment (markuswustenberg) [inline pkg/codegen/externalref.go:11]: I think it would be easier to understand if the param was `defs []*RequestBodyDefinition`, since the underlying def could be changed directly in that case, and you wouldn't need the `(*defs)[i] = rbd`. Or is there something I'm missing?

**Review by markuswustenberg — APPROVED** [review]
In my limited understanding of the internals of this project, LGTM. :D

File: pkg/codegen/externalref.go (hunk 7 above)
Comment (jamietanna) [reply pkg/codegen/externalref.go:11]: That's a fair shout.

I went for this solution, as I could just pass it in from `operations.go`:

```go
			ensureExternalRefsInRequestBodyDefinitions(&bodyDefinitions, pathItem.Ref)
```

Whereas if I went with that solution, I'd need to create a new slice that had a pointer to each value within `bodyDefinitions` :thinking:

File: internal/test/issues/issue-1378/bionicle/generate.go (hunk 5 above)
Comment (jamietanna) [reply internal/test/issues/issue-1378/bionicle/generate.go:3]: Short answer is yep!

Via https://www.jvt.me/posts/2022/06/15/go-tools-dependency-management/ and how that works.

As this is a submodule, we need to do https://github.com/deepmap/oapi-codegen/blob/5cdb5595bd38525b0a8f19cd322b91c0fb34b4d6/internal/test/go.mod#L1-L5 too

File: internal/test/issues/issue-1378/common/config.yaml (hunk 6 above)
Comment (jamietanna) [reply internal/test/issues/issue-1378/common/config.yaml:7]: Raised #1442 to cover this
